export const projects = [
  {
    id: '1',
    screenshot: '/dev-overflow.png',
    title: 'Finalecom-main-using-next.js',
    subTitle: 'Client project',
    stack: [
      'next.js',
      'typescript',
      'clerck',
      'tailwindcss',
      'mongodb',
      'mongoose',
      'clerck webhooks',
    ],
    description: `The client-facing e-commerce website is a beautifully designed platform tailored to showcase and sell premium photography products. Built with Next.js, the website delivers a seamless shopping experience by combining cutting-edge technology with visually appealing design. It caters to photographers and enthusiasts, offering them a curated collection of photography gear, prints, and accessories.`,
    date: 'Jan 31, 2025',
    github: 'https://github.com/Abhishekkute234/Finalecom-main-using-next.js.git',
    live: 'https://imagingv4.vercel.app/',
    color: 'rgba(249,115,22)',
    btnBg: 'rgba(154,52,18,0.5)',
    btnBgHover: 'rgba(67,20,7)',
    cardBg: 'rgba(154,52,18,0.05)',
  },
  {
    id: '2',
    screenshot: '/meta-market.png',
    title: 'Restaurant Authentication System using MERN stack',
    subTitle: 'Client Project',
    stack: [
      'react',
      'typescript',
      'tailwindcss',
      'nx',
      'rollup',
      'Module Federation',
      'vitest',
      'playwright',
      'storybook',
      'svgr',
      'lint-staged',
      'husky',
      'ci/cd',
      'aws',
    ],
    description:
      'I developed a full-stack Restaurant Authentication System using the MERN Stack (MongoDB, Express, React, Node.js). The system provides secure user authentication features, such as registration, login, and password management, allowing restaurants to manage their users efficiently.',
    date: 'Nov 19, 2024',
    github: 'https://github.com/Abhishekkute234/Restaurant-authentication-system-using-MERN-staxk.git',
    live: 'https://adproduction-2375.netlify.app/',
    color: 'rgba(139,92,246)',
    btnBg: 'rgba(91,33,182,0.5)',
    btnBgHover: 'rgba(46,16,101)',
    cardBg: 'rgba(91,33,182,0.05)',
  },
  {
    id: '3',
    screenshot: '/digital_scroll.png',
    title: 'Digital scroll',
    subTitle: 'Client project',
    stack: [
      'next.js',
      'typescript',
      'clerck',
      'tailwindcss',
      'mongodb',
      'mongoose',
      'clerck webhooks',
    ],
    description: `The client-facing e-commerce website is a beautifully designed platform tailored to showcase and sell premium photography products. Built with Next.js, the website delivers a seamless shopping experience by combining cutting-edge technology with visually appealing design. It caters to photographers and enthusiasts, offering them a curated collection of photography gear, prints, and accessories.`,
    date: 'Jan 31, 2025',
    github: 'https://github.com/Abhishekkute234/The-Digital-Scroll.git',
    live: 'https://the-digital-scroll.vercel.app/',
    color: 'rgba(249,115,22)',
    btnBg: 'rgba(154,52,18,0.5)',
    btnBgHover: 'rgba(67,20,7)',
    cardBg: 'rgba(154,52,18,0.05)',
  },

  {
    id: '4',
    screenshot: '/room-manager.png',
    title: 'Spam Guard',
    subTitle: 'Hackethon project',
    stack: [
      'react',
      'typescript',
      'tanstack',
      'styled component',
      'node',
      "api's",
      'express',
      'mongodb',
      'mongoose',
      'JWT',
      'cloudinary',
    ],
    description:
      'The Spam Detection and Prevention Tool is a project developed during a hackathon aimed at detecting and preventing spam across various communication channels. This tool provides users with the ability to detect spam messages, emails, multimedia messages (MMS), and short message service (SMS). Additionally, it includes functionality to determine whether phone numbers are associated with spam activity. Furthermore, the project integrates a chatbot where users can seek advice on how to stay safe from spam and fraud.',
    date: 'Sep 2, 2024',
    github: 'https://github.com/Abhishekkute234/SpamGuard.git',
    live: 'https://spam-detection-tool-1.onrender.com//',
    color: 'rgba(79,70,229)',
    btnBg: 'rgba(55,48,163,0.5)',
    btnBgHover: 'rgba(30,27,75)',
    cardBg: 'rgba(55,48,163,0.05)',
  },
  {
    id: '5',
    screenshot: '/image.png',
    title: 'Next Client agency webiste ',
    subTitle: 'Fintechracy official website',
    stack: ['react', 'tailwindcss', 'framer motion', 'shadcn'],
    description: `Fintechracy is on a mission to eliminate paper receipts by providing innovative software solutions. After two unsuccessful attempts to develop a professional website, I stepped in to deliver a final version that met the company's vision and market standards. The website, built with React, Tailwind CSS, ShadCN, and Framer Motion, features smooth animations, complete responsiveness, and multi-language support for a seamless global user experience.`,
    date: 'Jan 2, 2024',
    github: 'https://github.com/Abhishekkute234/Client-agency-webite.git',
    live: 'https://client-agency-webite-21qx.vercel.app/?__vercel_draft=1',
    color: 'rgba(34,197,94)',
    btnBg: 'rgba(22,101,52,0.5)',
    btnBgHover: 'rgba(5,46,22)',
    cardBg: 'rgba(22,101,52,0.05)',
  },

  {
    id: '6',
    screenshot: '/chatbotify.png',
    title: 'Static Client Agency Website',
    subTitle: 'Client agency webiste',
    stack: ['react', 'tailwindcss', 'figma'],
    description: `Static Client Agency Website`,
    date: 'Jan 2, 2024',
    github: 'https://github.com/Abhishekkute234/Agency-Website.git',
    live: 'https://adproduction-2375.netlify.app/',
    color: 'rgba(34,197,94)',
    btnBg: 'rgba(22,101,52,0.5)',
    btnBgHover: 'rgba(5,46,22)',
    cardBg: 'rgba(22,101,52,0.05)',
  },
];
